# Generated by Django 2.2.10 on 2020-11-19 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='choice_answer', to='polls.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='multiple_choice_answer',
            field=models.ManyToManyField(blank=True, null=True, related_name='multiple_choice_answer', to='polls.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(blank=True, verbose_name='Ответ'),
        ),
    ]
