# Generated by Django 2.2.10 on 2020-11-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201119_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='multiple_choice_answer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='choice_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice_answer',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Choice'),
        ),
    ]
